### ISSUE TITLE
Can't create a new wallet

### ISSUE THREAD

**Issue by spinza** [hivewallet/hive-android#19]
I previously installed your wallet and just checked it out so didn't note down the secret phrase.  I uninstalled the app.  Recently I decided to start using your app.  I installed Hive and it immediately went to a wallet on opening it.  It didn't ask to create a new wallet on launch.

I then did the following:
1. Opened application manager and force stop.
2. Clear data for Hive in applicaiton manager
3. Clear cache for Hive in applicaiton manager.
4. Uninstall the app
5.  Go to play store and install again
6. When I open Hive it goes straight to receiving address screen.  No option anywhere for creating a new wallet.
7. It does forget other settings such as display units / trusted peer etc.  These get dropped.
I like the app compared to others, but really would like to have the wallet secret phrase.
I'm using a Samsung Galaxy S5.  Standard issue.

**Comment by ghost** [comment]
@javgh Does Android have a single Web view storage for all apps?

**Comment by javgh** [comment]
> It does forget other settings such as display units / trusted peer etc. These get dropped.

Judging from this part, you are talking about our Hive Android Legacy app (this one: https://play.google.com/store/apps/details?id=com.hivewallet.androidclient.wallet ), since our new wallet does not yet allow changing the display units or have a "trusted peer" setting. The old Android client did not use a passphrase, so it will never ask for one.

Our current Hive Android app is this one: https://play.google.com/store/apps/details?id=com.hivewallet.hive.cordova . Resetting that one in the way you did should definitely make it ask for a passphrase again.

@spinza: Could you check which one of our Android wallets you were attempting to install?

**Comment by spinza** [comment]
Thanks,will have a look.

**Comment by spinza** [comment]
Ok definitely had the old wallet.  That sorted it thanks.
